name: Docker Image CI

on:
  push:
    paths: [ jwlee230/Program/Docker/* ]

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: make -C jwlee230/Program build
